# Generated by Django 2.0.7 on 2018-09-22 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('previous_college', models.CharField(blank=True, default='', max_length=200)),
                ('department', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, default='', max_length=150)),
                ('total_score', models.BigIntegerField(blank=True, default=0, verbose_name='Total score obtained as sum of reviews')),
                ('num_reviews', models.IntegerField(blank=True, default=0, verbose_name='Total number of reviews')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.College')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('review', models.CharField(blank=True, default='', max_length=2000)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.Professor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
