# Generated by Django 2.0.7 on 2018-11-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_auto_20181122_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_college', to='colleges.College'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='previous_college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_college', to='colleges.College'),
        ),
    ]
