# Generated by Django 2.0.7 on 2018-11-24 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_auto_20181124_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='college',
            field=models.ForeignKey(default='NULL', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='current_college', to='colleges.College'),
        ),
    ]
