# Generated by Django 2.0.7 on 2018-12-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0007_auto_20181124_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='qualifications',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
