# Generated by Django 2.0.7 on 2018-12-28 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0008_professor_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='previous_college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_college', to='colleges.College'),
        ),
    ]
