# Generated by Django 2.0.7 on 2018-12-28 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0009_auto_20181228_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
