# Generated by Django 2.0.7 on 2019-01-02 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professors', '0012_auto_20181231_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('title', models.CharField(default='-----', max_length=1000)),
                ('review', models.CharField(blank=True, default='', max_length=3000)),
                ('like_count', models.BigIntegerField(default=0)),
                ('dislike_count', models.BigIntegerField(default=0)),
                ('times_reported', models.IntegerField(default=0)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='ReportReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default=None, max_length=1000)),
                ('deleted_review', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.DeletedReviews')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='times_reported',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportreview',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.Review'),
        ),
    ]
