# Generated by Django 2.0.7 on 2019-01-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0013_auto_20190102_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportreview',
            name='reason',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
