# Generated by Django 2.0.7 on 2018-09-22 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=10000)),
                ('city', models.CharField(default='', max_length=300)),
                ('state', models.CharField(default='', max_length=300)),
                ('zipcode', models.IntegerField(blank=True)),
                ('phoneNumber', models.CharField(blank=True, default='', max_length=15)),
                ('websiteUri', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('google_rating', models.FloatField(blank=True, default=0)),
                ('total_rating', models.FloatField(blank=True, default=0)),
                ('number_ratings', models.IntegerField(blank=True, default=0)),
                ('attributions', models.CharField(blank=True, default='', max_length=200)),
                ('city_id', models.CharField(max_length=200)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
