# Generated by Django 2.0.7 on 2018-11-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
