# Generated by Django 2.0.7 on 2018-11-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_auto_20181108_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='total_rating',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
