# Generated by Django 2.0.7 on 2018-12-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_auto_20181124_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='phoneNumber',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
