# Generated by Django 2.0.7 on 2018-09-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_useractivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivation',
            name='activation_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
