# Generated by Django 2.0.7 on 2018-10-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181021_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivation',
            name='atempt_datetime',
        ),
        migrations.AddField(
            model_name='useractivation',
            name='attempt_datetime',
            field=models.FloatField(default=1540098032.6107283),
        ),
    ]
