# Generated by Django 2.0.7 on 2018-11-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181108_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='passing_year',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='attempt_datetime',
            field=models.FloatField(default=1542849677.531154),
        ),
    ]
